### ISSUE TITLE
Ensure VocExcel conforms to latest version of VocPub

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/VocExcel#8]
Using the templates from QSI Roads vocabs, they were not conforming and did not display the concepts hierarchy in the UI.

**Comment by edmondchuc** [comment]
This may be resolved by https://github.com/RDFLib/VocExcel/commit/15ffff784e0ebe68fdf3cf59e514e0768fb90a7c.

**Comment by nicholascar** [comment]
VocExcel 0.7.x in Kurrawong's repo, https://github.com/Kurrawong/VocExcel, produces output that is valid according to VocPub 4.6+
